import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { ThemeProvider } from "@/components/theme-provider";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";


const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap", // ensures fallback font shows until Inter loads
  fallback: ["system-ui", "Helvetica", "Arial", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Mahesha BR - Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` ${inter.className} selection:bg-black selection:text-white dark:selection:bg-neutral-50 dark:selection:text-black antialiased scroll-smooth`}
      >
        <Toaster/>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NavBar />
          <div className="w-full scroll-smooth">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}

// max-w-3xl mx-auto
// border-x
// border-neutral-800
